name = "WeirdMatrices"
uuid = "0ab8aefd-a72a-459c-b9b7-009309dcfd2a"
authors = ["Stefanos Carlström <stefanos.carlstrom@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
